# Generated by Django 4.1.7 on 2023-04-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set(),
        ),
    ]
