# Generated by Django 4.1.7 on 2023-04-23 05:30

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_photo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, upload_to=albums.models.get_cover_upload_path, verbose_name='файл'),
        ),
    ]
