# Generated by Django 4.1.7 on 2023-04-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-is_confirmed', '-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
